# Generated by Django 3.1.7 on 2021-05-18 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_auto_20210518_2048'),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.branch'),
        ),
        migrations.AlterField(
            model_name='quiz_questions',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='results',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.branch'),
        ),
    ]
