# Generated by Django 3.2.2 on 2021-05-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_auto_20210426_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_questions',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
