# Generated by Django 3.1.7 on 2021-06-13 08:57

import curriculum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_auto_20210518_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='image',
            field=models.ImageField(blank=True, upload_to=curriculum.models.save_branch_image, verbose_name='Branch Image'),
        ),
    ]
